#relevant/minimal hmc python libs on 10-02-2023 (full list raises many errors)
#temporarily using scipy non-fixed version, since scipy==1.3.1 raises numpy library errors (https://github.com/Deltares/hatyan/issues/71)
#statsmodels is not yet available at HMC (needed for KWK), so temporarily using non-fixed version
#pytest, pytest-cov, jupyter, notebook, bumpversion, twine are added for local maintenance, so using non-fixed versions
name: hatyan_hmcenv
dependencies:
  - python==3.8.13
  - pip==22.3.1
  - pip:
    - matplotlib==3.6.2
    - netCDF4==1.6.2
    - numpy==1.23.5
    - pandas==1.5.2
    - pyproj==3.3.1
    - requests==2.28.1
    #- scipy==1.3.1
    - scipy
    - seaborn==0.12.1
    - sip==6.7.5
    - six==1.16.0
    - spyder==5.4.0
    - xarray==2022.12.0
    - statsmodels
    - pytest
    - pytest-cov
    - jupyter
    - notebook
    - bumpversion
    - twine
