#relevant/minimal hmc python libs on 02-03-2023 (full list raises many errors)
name: hatyan_hmcenv
dependencies:
  - python==3.8.13
  - pip==22.3.1
  - pip:
    - matplotlib==3.6.3
    - netCDF4==1.6.2
    - numpy==1.23.5
    - pandas==1.5.3
    - pyproj==3.3.1
    - requests==2.28.2
    - scipy==1.10.0
    - seaborn==0.12.2
    - sip==6.7.7
    - six==1.16.0
    - spyder==5.4.2
    - xarray==2022.12.0
    - statsmodels==0.13.5
