#hmc python libs on 17-08-2022
name: hatyan_devenv
dependencies:
  - python==3.8.11
  - pip>=19.2.3
  - pip:
    - alabaster==0.7.12
    - altair==4.2.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.2
    - astroid==2.6.6
    - asttokens==2.0.5
    - atomicwrites==1.4.0
    - attrs==21.4.0
    - autopep8==1.5.7
    - Babel==2.10.3
    - backcall==0.2.0
    #- basemap @ file:///home/kwok/vortechpackages/rpmbuild/BUILD/basemap-1.2.2rel
    - beautifulsoup4==4.11.1
    - binaryornot==0.4.4
    - black==22.6.0
    - bleach==5.0.1
    - certifi==2022.6.15
    - cffi==1.15.1
    - cftime==1.6.1
    - cfunits==3.3.4
    - chardet==5.0.0
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cloudpickle==2.1.0
    - cookiecutter==2.1.1
    - coverage==6.4.1
    - cryptography==37.0.2
    - cycler==0.11.0
    - Cython==0.29.30
    - dataclasses==0.6
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - diff-match-patch==20200713
    - docutils==0.18.1
    - entrypoints==0.4
    - ESMPy==8.1.0
    - et-xmlfile==1.1.0
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - feather-format==0.4.1
    - flake8==3.9.2
    - Flask==2.1.2
    - fonttools==4.33.3
    - idna==3.3
    - imagesize==1.4.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.8.0
    - inflection==0.5.1
    - iniconfig==1.1.1
    - intervaltree==3.1.0
    - ipykernel==6.15.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - isort==5.10.1
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jeepney==0.8.0
    - Jinja2==3.1.2
    - jinja2-time==0.2.0
    - json5==0.9.8
    - jsonschema==4.6.1
    - jupyter-client==6.1.12
    - jupyter-core==4.10.0
    - jupyter-server==1.18.0
    - jupyterlab==3.4.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.14.0
    - keyring==23.6.0
    - kiwisolver==1.4.3
    - lazy-object-proxy==1.7.1
    - MarkupSafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - mypy==0.961
    - mypy-extensions==0.4.3
    - nbclassic==0.4.0
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - netCDF4==1.6.0
    - netcdftime==1.0.0a2
    - notebook-shim==0.1.0
    - numpy==1.23.0
    - numpydoc==1.4.0
    - openpyxl==3.0.10
    - packaging==21.3
    - pandas==1.4.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pep8==1.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==9.2.0
    - pluggy==1.0.0
    - ply==3.11
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pyarrow==8.0.0
    - pycodestyle==2.7.0
    - pycparser==2.21
    - pydocstyle==6.1.1
    - pyflakes==2.3.1
    - pygame==2.1.2
    - Pygments==2.12.0
    - pygrib==2.1.4
    - pylint==2.9.6
    - pyls-spyder==0.4.0
    - pyparsing==3.0.9
    - pyproj==3.3.1
    - PyQt5==5.12.3
    - PyQt5-sip==12.11.0
    - PyQtWebEngine==5.12.1
    - pyrsistent==0.18.1
    - pyshp==2.3.0
    - pytest==7.1.2
    - pytest-cov==3.0.0
    - python-dateutil==2.8.2
    - python-lsp-black==1.1.0
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.2.4
    - python-slugify==6.1.2
    - pytoolconfig==1.2.1
    - pytz==2022.1
    - pyxdg==0.28
    - PyYAML==6.0
    - pyzmq==23.2.0
    - QDarkStyle==3.0.2
    - qstylizer==0.2.1
    - QtAwesome==1.1.1
    - qtconsole==5.1.1
    - QtPy==2.1.0
    - requests==2.28.1
    - rope==1.2.0
    - Rtree==1.0.0
    - scipy==1.3.1
    - seaborn==0.11.2
    - SecretStorage==3.3.2
    - Send2Trash==1.8.0
    - sip==6.6.2
    - six==1.16.0
    - sniffio==1.2.0
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - Sphinx==5.0.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - spyder==5.1.5
    - spyder-kernels==2.1.3
    - stack-data==0.3.0
    - terminado==0.15.0
    - text-unidecode==1.3
    - textdistance==4.3.0
    - three-merge==0.1.1
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.11.2
    - tornado==6.2
    - traitlets==5.3.0
    - types-dataclasses==0.6.6
    - typing_extensions==4.3.0
    - ujson==5.4.0
    - urllib3==1.26.9
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - Werkzeug==2.1.2
    - wrapt==1.12.1
    - wurlitzer==3.0.2
    - xarray==2022.10.0
    - yapf==0.32.0
    - zipp==3.8.0
