[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hatyan"
version = "2.14.1"
maintainers = [{ name = "Jelmer Veenstra", email = "jelmer.veenstra@deltares.nl" }]
description = "Tidal analysis and prediction tool of Rijkswaterstaat"
readme = "README.md"
keywords = ["hatyan", "tidal analysis", "tidal prediction"]
license = "LGPL-3.0"
requires-python = ">=3.9"
dependencies = [
	#scipy>=1.5.4 env creation succeeded in https://github.com/Deltares/hatyan/issues/71
	"scipy>=1.5.4",
	#numpy>=1.24.0 is oldest supported version in Q4 2024
	"numpy>=1.24.0",
	#matplotlib>=3.7.0 contour colorbar on uniform values succeeds
	"matplotlib>=3.7.0",
	#pandas>=2.1.0 has persistent max attrs (test_metadata_persistence)
	"pandas>=2.1.0",
	#netcdf4>=1.5.6 does not call numpy.bool (avoids AttributeError)
	"netcdf4>=1.5.6",
	#pyproj>=3.1.0 is pip installable in py38
	"pyproj>=3.1.0",
	#requests>=2.28.0 was tested on hmc
	"requests>=2.28.0",
	#xarray>=2023.4.0 does not conflict with pandas<2.0.0 for resampling
	"xarray>=2023.4.0",
	#rws-ddlpy>=0.9.3 added caching for ddlpy.locations() including dependency
	"rws-ddlpy>=0.9.3",
	#click>=7.1 is the first version available on github release page
	"click>=7.1",
]
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: Science/Research",
	"Operating System :: OS Independent",
	"Topic :: Scientific/Engineering :: Information Analysis",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: 3.14",
]

[project.urls]
Home = "https://github.com/deltares/hatyan"
Code = "https://github.com/deltares/hatyan"
Issues = "https://github.com/deltares/hatyan/issues"

[project.optional-dependencies]
dev = [
	"bump2version>=0.5.11",
	"flake8",
	"flake8-pyproject", # required to read the config from pyproject.toml
	"pytest",
	"pytest-cov",
	"twine",
	"build",
]
docs = [
	"sphinx>=1.8.1",
	"sphinx_mdinclude",
	"nbsphinx",
	"pydata-sphinx-theme",
	#"pandoc", # installed with choco on github
]
examples = [
	"jupyter",
	"notebook",
]

[project.scripts]
hatyan = "hatyan.cli:cli"

[tool.setuptools.package-data]
hatyan = ["data/*"]

[tool.pytest.ini_options]
console_output_style = "count"
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "-v --tb=short --durations=0"
filterwarnings = [
	"error",
	"ignore::UserWarning",
    # TODO: ignore numpy warning after fixing https://github.com/Deltares/hatyan/issues/435
    "ignore:Setting the shape on a NumPy array has been deprecated in NumPy 2.5:DeprecationWarning",
	]
markers = [
	"unittest: mark a test as unittest. Used for testing single methods",
	"systemtest: mark a test as systemtest. Used for testing at a higher level, verifying a given input returns the expected output",
	"acceptance: mark a test as acceptance. Used for non-functional requirements and data that needs to be human-verified",
]

[tool.flake8]
exclude = "docs,.pixi"
# ignore star import (F401+F403).
# ignore whitespace before ':' (E203)
# ignore line too long (E501), necessary for docstrings
#extend-ignore = "F401,F403,E203,E501"
# TODO: resolve many flake8 errors instead of ignoring them: https://github.com/Deltares/hatyan/issues/433
extend-ignore = "F401,F403,E203,E501,C901,E111,E124,E127,E128,E131,E201,E202,E221,E222,E225,E228,E231,E251,E261,E262,E265,E266,E301,E302,E303,E402,E713,E721,W291,W292,W293,W391"
# same maxlinelenght as black.
max-line-length = 88
max-complexity = 10
statistics = "True"


## Pixi related entries
[tool.pixi.workspace]
channels  = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.feature.test.tasks]
test = { cmd = ["pytest", "--cov=hatyan", "--cov-report=xml", "--cov-report=term"] }

[tool.pixi.feature.docs.tasks]
docs-build = { cmd = ["sphinx-build", "docs", "docs/_build"] }

# Install your code in editable mode, dependencies here are installed in all environments
# Takes the dependencies from pyproject.toml, which will be overridden in the features below.
[tool.pixi.pypi-dependencies]
hatyan = { path = ".", editable = true }

[tool.pixi.feature.minimal.pypi-dependencies]
# the versions are a manual copy of [project.dependencies],
# but with == to test with the lowest versions of direct dependencies
scipy = "==1.5.4"
numpy = "==1.24.0"
matplotlib = "==3.7.0"
pandas = "==2.1.0"
netcdf4 = "==1.5.6"
pyproj = "==3.1.0"
requests = "==2.28.0"
xarray = "==2023.4.0"
rws-ddlpy = "==0.9.3"
click = "==7.1"

# Define features for different Python versions and Hydromt versions
[tool.pixi.feature.py39.dependencies]
python = "3.9.*"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"

[tool.pixi.feature.py314.dependencies]
python = "3.14.*"

[tool.pixi.feature.docs.dependencies]
pandoc = "*"

# Define environments to combine features
[tool.pixi.environments]
default = { features = ["py314", "dev", "docs", "examples", "test"]}

dev = { features = ["py314", "dev"]}

py39 = { features = ["py39", "dev", "test"]}
py310 = { features = ["py310", "dev", "test"]}
py311 = { features = ["py311", "dev", "test"]}
py312 = { features = ["py312", "dev", "test"]}
py313 = { features = ["py313", "dev", "test"]}
py314 = { features = ["py314", "dev", "test"]}

py39-mindeps = { features = ["py39", "dev", "test", "minimal"]}
