name: generate-documentation

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        conda env update --file environment.yml --name base
        #python -m pip install pdoc3 pandoc
        #pip install -r requirements.txt
        python setup.py build test
    - name: Generate documentation
      run: |
        pdoc --html hatyan -o docs --force --config sort_identifiers=False
    - name: Commit updated documentation
      run: |
        git config --global user.name 'veenstrajelmer'
        git add docs/hatyan/*
        git commit -a -m "Updated documentation" --no-verify
        git push
